### ISSUE TITLE
TypeError on Pro Version after updating to Livewire v3.7

### ISSUE THREAD

**Issue by EriksonEnterprises** [wire-elements/pro-demo#20]
After updating livewire to v3.7 I get:

```
TypeError
vendor/wire-elements/pro/src/Components/Modal/Foundation/Base.php:51
Illegal offset type in unset
```

I think this is the fix:

```
public function removeComponentFromState($id)
    {
        // Add type checking and conversion
        if (is_array($id)) {
            $id = $id['id'] ?? $id[0] ?? null;
        }
        
        if (is_object($id)) {
            $id = method_exists($id, '__toString') ? (string) $id : null;
        }
        
        if ($id !== null && isset($this->components[$id])) {
            unset($this->components[$id]);
        }
    }
```

**Comment by PhiloNL** [comment]
Hi @EriksonEnterprises 
This has been fixed in the latest release both v4 and v5:
https://changelog.anystack.sh/wire-elements-pro

**Comment by EriksonEnterprises** [comment]
I'm still having the error unless I edit the vendor file directly. I tried deleting everything and installing wire-elements-pro v5.0.5 but the error still persists

I'm not able to install v5.0.7, is that the one that has the fix?

This error pops up when I open/close modals numerous times on the same page (Without reloading the page)
